import type { PsychoContent, PsychoRecord } from "./psychoeducation";

/**
 * Gepubliceerde startcatalogus voor de tegel Leren.
 * Laat een professional de teksten, bronnen en zoektermen controleren vóór
 * gebruik in een productieomgeving. Nieuwe items kunnen via het beheer als
 * concept worden geïmporteerd en gepubliceerd.
 */
const source = (title: string, url: string) => [{ title, url }];

const item = (
  content: Omit<PsychoContent, "schemaVersion" | "languageLevel" | "video" | "author"> &
    Partial<Pick<PsychoContent, "languageLevel" | "video" | "author">>,
): PsychoRecord => ({
  content: {
    schemaVersion: 1,
    languageLevel: "simpel",
    video: null,
    author: "RecoveryBuddy-redactie — professioneel te controleren",
    ...content,
  },
  revision: 1,
  status: "published",
  review: {
    reviewer: "RecoveryBuddy-redactie — controleer vóór productiegebruik",
    reviewedAt: "2026-09-15T00:00:00.000Z",
    revision: 1,
  },
});

export const psychoeducationSeed: PsychoRecord[] = [
  item({
    id: "coping-toen-en-nu",
    title: "Coping toen en nu: wat je vroeger hielp",
    summary: "Over gewoonten die je hielpen omgaan met spanning, maar later niet altijd meer passen.",
    topics: ["Coping", "Grenzen", "Emoties"],
    keywords: ["coping", "pleasen", "aanpassen", "nee zeggen", "grenzen", "gevoelens", "conflict vermijden"],
    exampleQueries: ["Ik zeg altijd ja", "Ik probeer iedereen tevreden te houden", "Ik durf geen nee te zeggen", "Ik ben bang dat mensen boos worden", "Ik laat mijn gevoelens niet zien"],
    paragraphs: [
      "Als kind leer je manieren om met moeilijke situaties om te gaan. Misschien hield je goed in de gaten hoe anderen zich voelden, paste je je aan of liet je weinig van je eigen gevoelens zien. Dat kon helpen om spanning te verminderen of je veiliger te voelen.",
      "Zo'n manier van reageren kan een gewoonte worden. Later doe je het misschien nog steeds, ook als een situatie meer ruimte biedt om jezelf te zijn.",
      "Steeds ja zeggen kan bijvoorbeeld rust geven, maar ook betekenen dat er weinig ruimte overblijft voor wat jij nodig hebt. Dat betekent niet dat je iets verkeerd doet: een oude beschermingsstrategie past misschien niet meer bij elke situatie.",
      "Je hoeft de gewoonte niet meteen los te laten. Begin met opmerken wat je doet, waar het bij helpt en wat het kost. Probeer in een veilige situatie eventueel iets anders, samen met je behandelaar.",
    ],
    reflectionQuestion: "Herken je een gewoonte die je helpt, maar soms ook iets kost?",
    suggestedAction: "Merk deze week één moment op waarop je automatisch ja zegt.",
    sources: source("National Child Traumatic Stress Network — Effects of complex trauma", "https://www.nctsn.org/what-is-child-trauma/trauma-types/complex-trauma/effects"),
  }),
  item({
    id: "vroege-signalen-terugval",
    title: "Vroege signalen van terugval herkennen",
    summary: "Kleine veranderingen kunnen laten zien dat extra steun of rust nodig is.",
    topics: ["Terugval", "Zelfmanagement", "Signalen"],
    keywords: ["terugval", "waarschuwingssignalen", "vroegsignalen", "slechter", "ontregeling", "hulp zoeken"],
    exampleQueries: ["Hoe merk ik dat het slechter gaat", "Wat zijn mijn eerste signalen", "Ik raak weer ontregeld"],
    paragraphs: [
      "Een terugval begint niet altijd plotseling. Vaak zijn er eerder veranderingen, zoals slechter slapen, meer piekeren, minder eten, sneller geïrriteerd zijn of contact vermijden.",
      "De signalen verschillen per persoon. Het helpt om samen met je behandelaar en naasten jouw persoonlijke signalen op te schrijven.",
      "Een vroeg signaal is geen bewijs dat er zeker een terugval komt. Het is een uitnodiging om te kijken wat je nodig hebt: rust, structuur, contact of overleg met je behandelteam.",
    ],
    reflectionQuestion: "Welke verandering merken jij of anderen meestal als eerste?",
    suggestedAction: "Noteer drie vroege signalen en één helpende actie per signaal.",
    sources: source("GGZ Standaarden — Zelfmanagement", "https://www.ggzstandaarden.nl/zorgstandaarden/zelfmanagement/afsluiten"),
  }),
  item({
    id: "crisisplan-veiligheid",
    title: "Crisisplan en veiligheidsafspraken",
    summary: "Vooraf opschrijven wie je belt en wat helpt, maakt handelen in een crisis makkelijker.",
    topics: ["Crisis", "Veiligheid", "Plan"],
    keywords: ["crisisplan", "veiligheidsplan", "noodplan", "crisisdienst", "112", "acute hulp"],
    exampleQueries: ["Wat doe ik in een crisis", "Wie kan ik bellen", "Ik voel me niet veilig"],
    paragraphs: [
      "Een crisisplan beschrijft wat jij en anderen kunnen doen wanneer de spanning sterk oploopt. Zet er herkenbare signalen, helpende stappen en telefoonnummers in.",
      "Bespreek het plan met je behandelaar en met mensen die je toestemming geeft om te helpen. Bewaar het op een plek waar je het snel kunt vinden.",
      "Bij direct gevaar voor jezelf of een ander: blijf niet alleen en neem direct contact op met de crisisdienst of 112. Deze tekst vervangt geen acute beoordeling.",
    ],
    reflectionQuestion: "Wie mag jij bellen als je je niet veilig voelt?",
    suggestedAction: "Vul samen met je behandelaar één eerste crisisafspraak in.",
    sources: source("Zorg voor Beter — Zelfmanagementondersteuning in de ggz", "https://www.zorgvoorbeter.nl/kennisbundel-zelfmanagement/gezondheidsvaardigheden/zelfmanagementondersteuning-in-de-ggz"),
  }),
  item({
    id: "slaap-en-dag-nachtritme",
    title: "Slaap en dag-nachtritme",
    summary: "Slaap beïnvloedt stemming, spanning en herstel; kleine vaste stappen kunnen helpen.",
    topics: ["Slaap", "Ritme", "Herstel"],
    keywords: ["slapen", "inslapen", "doorslapen", "ritme", "moe", "nacht"],
    exampleQueries: ["Ik slaap slecht", "Hoe krijg ik ritme", "Ik ben al dagen wakker"],
    paragraphs: [
      "Een onregelmatig ritme kan klachten versterken. Tegelijk kan slecht slapen ook een gevolg zijn van stress, stemming, middelen of medicatie.",
      "Een vaste opsta-tijd, daglicht en een kleine haalbare activiteit overdag zijn vaak een goed begin. Probeer veranderingen rustig uit en bespreek aanhoudende problemen.",
      "Meerdere nachten bijna niet slapen, vooral samen met veel energie of impulsief gedrag, kan een vroeg signaal van ontregeling zijn. Neem dan contact op met je behandelteam.",
    ],
    reflectionQuestion: "Welke kleine verandering maakt jouw ochtend iets voorspelbaarder?",
    suggestedAction: "Kies voor drie dagen een vaste opsta-tijd.",
    sources: source("NHS — How to get to sleep", "https://www.nhs.uk/every-mind-matters/mental-health-issues/sleep/"),
  }),
  item({
    id: "medicatie-doel-en-werking",
    title: "Medicatie: doel en werking",
    summary: "Samen begrijpen waarvoor medicatie bedoeld is, helpt bij samen beslissen.",
    topics: ["Medicatie", "Behandeling", "Samen beslissen"],
    keywords: ["medicijnen", "medicatie", "werking", "dosering", "psychiater", "behandeling"],
    exampleQueries: ["Waarom krijg ik dit medicijn", "Hoe werkt mijn medicatie", "Wanneer merk ik effect"],
    paragraphs: [
      "Psychiatrische medicatie kan verschillende doelen hebben, zoals het verminderen van angst, somberheid, psychotische ervaringen of sterke stemmingswisselingen.",
      "Het effect en de tijd tot effect verschillen per middel en persoon. Vraag je behandelaar welk doel, welke verwachte werking en welke controles bij jouw medicijn horen.",
      "Verander de dosis niet zelf en stop niet plotseling zonder overleg. Samen kun je baten, nadelen en alternatieven bespreken.",
    ],
    reflectionQuestion: "Welk doel van je medicatie wil je met je behandelaar verduidelijken?",
    suggestedAction: "Schrijf één vraag over je medicatie op voor het volgende contact.",
    sources: source("NHS — Medicines information", "https://www.nhs.uk/conditions/medicines-information/"),
  }),
  item({
    id: "medicatie-bijwerkingen",
    title: "Medicatie: bijwerkingen herkennen en bespreken",
    summary: "Bijwerkingen zijn bespreekbaar; noteer wat je merkt en wanneer het begon.",
    topics: ["Medicatie", "Bijwerkingen", "Lichamelijke gezondheid"],
    keywords: ["bijwerking", "misselijk", "slaperig", "gewicht", "onrust", "contact behandelaar"],
    exampleQueries: ["Is deze bijwerking normaal", "Ik ben zo slaperig van mijn medicatie", "Wat moet ik melden"],
    paragraphs: [
      "Bijwerkingen kunnen lichamelijk of psychisch zijn en kunnen in de loop van de tijd veranderen. Niet iedere klacht komt door medicatie, maar het is altijd zinvol deze te bespreken.",
      "Noteer middel, dosis, tijdstip, klacht en invloed op je dagelijks leven. Zo kan je behandelaar beter meedenken over aanpassing, controle of een alternatief.",
      "Bij ernstige of snel toenemende klachten, allergische verschijnselen of acute onveiligheid: zoek direct medische hulp.",
    ],
    reflectionQuestion: "Welke klacht wil je concreet bijhouden?",
    suggestedAction: "Houd drie dagen tijdstip en ernst van de klacht bij.",
    sources: source("Lareb — Bijwerkingen melden en informatie", "https://www.lareb.nl/melden/"),
  }),
  item({
    id: "angst-en-paniek",
    title: "Angst en paniek begrijpen",
    summary: "Paniek voelt gevaarlijk, maar is vaak een sterke alarmreactie van het lichaam.",
    topics: ["Angst", "Paniek", "Lichaamsreacties"],
    keywords: ["angst", "paniek", "hyperventilatie", "hartkloppingen", "vermijden", "alarm"],
    exampleQueries: ["Wat gebeurt er bij paniek", "Ik krijg hartkloppingen", "Hoe stop ik een paniekaanval"],
    paragraphs: [
      "Bij paniek gaat het alarmsysteem van je lichaam aan. Hartslag, ademhaling en spierspanning kunnen toenemen. Dat voelt heftig, ook als er op dat moment geen direct gevaar is.",
      "Langzaam uitademen, je voeten voelen en benoemen wat je ziet kunnen helpen om weer in het hier-en-nu te komen. Vermijden geeft soms kort rust, maar kan angst op langere termijn groter maken.",
      "Nieuwe, ernstige of lichamelijk onverklaarde klachten verdienen medische beoordeling.",
    ],
    reflectionQuestion: "Welke vroege lichaamssensatie herken je bij angst?",
    suggestedAction: "Oefen één minuut rustig uitademen wanneer je kalm bent.",
    sources: source("NHS — Panic disorder", "https://www.nhs.uk/mental-health/conditions/panic-disorder/"),
  }),
  item({
    id: "psychose-en-stemmen",
    title: "Psychose en stemmen horen",
    summary: "Ongewone ervaringen kunnen echt en beangstigend voelen; je hoeft ze niet alleen te begrijpen.",
    topics: ["Psychose", "Stemmen", "Ongewone ervaringen"],
    keywords: ["psychose", "stemmen", "hallucinaties", "wanen", "achterdocht", "realiteit"],
    exampleQueries: ["Ik hoor stemmen", "Ik zie dingen", "Hoe weet ik wat echt is", "Mijn gedachten maken me bang"],
    paragraphs: [
      "Sommige mensen horen stemmen, voelen zich bekeken of ervaren gedachten als bijzonder overtuigend. Zulke ervaringen kunnen samenhangen met stress, slaaptekort, middelen of psychische kwetsbaarheid.",
      "Je hoeft niet meteen te beslissen wat een ervaring precies betekent. Rust, voorspelbaarheid en contact met een vertrouwd persoon kunnen helpen.",
      "Bespreek veranderingen snel met je behandelteam. Bij opdrachten van stemmen, ernstige angst of direct gevaar: zoek onmiddellijk hulp.",
    ],
    reflectionQuestion: "Wie helpt jou om ervaringen rustig te onderzoeken?",
    suggestedAction: "Noteer wanneer de ervaring optreedt en wat eraan voorafging.",
    sources: source("NICE — Psychosis and schizophrenia in adults", "https://www.nice.org.uk/guidance/cg178"),
  }),
  item({
    id: "emoties-reguleren",
    title: "Emoties herkennen en reguleren",
    summary: "Emoties geven informatie; leren vertragen maakt kiezen soms weer mogelijk.",
    topics: ["Emoties", "Regulatie", "Spanning"],
    keywords: ["emotieregulatie", "boos", "verdriet", "impulsief", "overweldigd", "kalmeren"],
    exampleQueries: ["Mijn emoties zijn te sterk", "Ik reageer impulsief", "Hoe word ik rustiger"],
    paragraphs: [
      "Emoties ontstaan vaak snel en hebben een functie. Het doel is niet om emoties weg te maken, maar om ze eerder op te merken en ruimte te maken voor een keuze.",
      "Een korte pauze, benoemen wat je voelt, bewegen of contact zoeken kan helpen. Wat werkt verschilt per persoon en situatie.",
      "Als emoties leiden tot zelfbeschadiging, agressie of andere onveiligheid, bespreek dan een persoonlijk veiligheidsplan met je behandelaar.",
    ],
    reflectionQuestion: "Welke emotie merk je het eerst in je lichaam?",
    suggestedAction: "Gebruik vandaag één woord om je belangrijkste emotie te benoemen.",
    sources: source("GGZ Standaarden — Zelfmanagement", "https://www.ggzstandaarden.nl/zorgstandaarden/zelfmanagement/afsluiten"),
  }),
  item({
    id: "middelen-en-psychische-klachten",
    title: "Alcohol, cannabis en andere middelen",
    summary: "Middelen kunnen tijdelijk verlichting geven, maar ook klachten, slaap en behandeling beïnvloeden.",
    topics: ["Middelen", "Alcohol", "Cannabis", "Herstel"],
    keywords: ["alcohol", "cannabis", "drugs", "middelengebruik", "verslaving", "onttrekking"],
    exampleQueries: ["Heeft cannabis invloed op mijn klachten", "Ik gebruik om rustig te worden", "Kan ik drinken met mijn medicatie"],
    paragraphs: [
      "Een middel kan op korte termijn spanning, slapeloosheid of nare gedachten dempen. Later kunnen stemming, angst, slaap, motivatie of psychotische ervaringen juist verslechteren.",
      "Vertel je behandelaar eerlijk wat, hoeveel en wanneer je gebruikt. Dat is nodig om risico's en medicatie veilig te beoordelen.",
      "Plotseling stoppen kan bij sommige middelen gevaarlijk zijn. Bespreek minderen of stoppen daarom met een professional.",
    ],
    reflectionQuestion: "Wat levert gebruik je op, en welke nadelen merk je?",
    suggestedAction: "Noteer één week lang middel, hoeveelheid, moment en effect.",
    sources: source("Trimbos-instituut — Alcohol en psychische gezondheid", "https://www.trimbos.nl/kennis/alcohol/"),
  }),
  item({
    id: "act-psychologische-flexibiliteit",
    title: "ACT: psychologische flexibiliteit",
    summary: "ACT helpt je ruimte te maken voor wat je voelt en tegelijk te handelen in de richting van wat belangrijk is.",
    topics: ["ACT", "Psychologische flexibiliteit", "Herstel"],
    keywords: ["act", "psychologische flexibiliteit", "ruimte maken", "waarden", "keuzes", "herstel"],
    exampleQueries: ["Wat is ACT", "ACT bij spanning", "Hoe werkt psychologische flexibiliteit", "Wat kan ik met ACT oefenen"],
    paragraphs: [
      "ACT staat voor Acceptance and Commitment Therapy. ACT gaat niet alleen over minder klachten. Het gaat ook over leren omgaan met moeilijke gedachten en gevoelens, zodat je kunt blijven doen wat voor jou belangrijk is.",
      "Psychologische flexibiliteit betekent dat je kunt opmerken wat er in je gebeurt, ruimte kunt maken voor je ervaring en vervolgens een bewuste stap kunt kiezen.",
      "Een moeilijke gedachte of gevoel hoeft dus niet eerst weg te zijn voordat je iets waardevols kunt doen. Oefenen gaat stap voor stap en binnen wat op dit moment haalbaar is.",
    ],
    reflectionQuestion: "Wat zou je vandaag willen doen als je moeilijke gevoelens even mee mogen reizen?",
    suggestedAction: "Kies één kleine actie die past bij wat voor jou belangrijk is en plan die in.",
    sources: source("Association for Contextual Behavioral Science — ACT", "https://contextualscience.org/act"),
  }),
  item({
    id: "act-waarden-en-richting",
    title: "ACT: waarden en richting kiezen",
    summary: "Waarden zijn kwaliteiten van leven die richting geven aan kleine keuzes.",
    topics: ["ACT", "Waarden", "Richting"],
    keywords: ["act", "waarden", "richting", "wat belangrijk is", "betekenis", "keuze"],
    exampleQueries: ["Wat vind ik belangrijk", "ACT waarden oefening", "Hoe kies ik richting", "Waar wil ik voor staan"],
    paragraphs: [
      "Een waarde is geen doel dat je op een dag afvinkt. Het is een richting of kwaliteit die je steeds opnieuw kunt meenemen, bijvoorbeeld zorgzaamheid, eerlijkheid, verbondenheid, moed of nieuwsgierigheid.",
      "Waarden zijn persoonlijk. Het gaat niet om wat anderen belangrijk vinden of wat je zou moeten kiezen.",
      "Als je een waarde hebt gekozen, kun je vragen: welke kleine actie past hier vandaag bij, ook als het lastig voelt?",
    ],
    reflectionQuestion: "Welke kwaliteit wil je vandaag in je contact met jezelf of een ander laten zien?",
    suggestedAction: "Schrijf één waarde op en koppel daar één actie van maximaal tien minuten aan.",
    sources: source("Association for Contextual Behavioral Science — ACT", "https://contextualscience.org/act"),
  }),
  item({
    id: "act-gedachten-opmerken",
    title: "ACT: gedachten opmerken zonder ze te volgen",
    summary: "Je kunt een gedachte opmerken zonder automatisch te doen wat de gedachte zegt.",
    topics: ["ACT", "Gedachten", "Defusie"],
    keywords: ["act", "gedachten", "defusie", "piekeren", "afstand nemen", "denken"],
    exampleQueries: ["Hoe neem ik afstand van gedachten", "ACT gedachten", "Ik blijf maar piekeren", "Mijn gedachten bepalen alles"],
    paragraphs: [
      "Gedachten zijn mentale gebeurtenissen. Ze kunnen nuttig zijn, maar ze zijn niet altijd feiten, opdrachten of voorspellingen.",
      "Bij defusie oefen je om een gedachte als gedachte te herkennen. Daardoor kan er iets meer ruimte ontstaan tussen wat je denkt en wat je doet.",
      "Het doel is niet om positieve gedachten te forceren of gedachten weg te duwen.",
    ],
    reflectionQuestion: "Welke gedachte neemt op dit moment veel ruimte in? Kun je beginnen met: ‘Ik merk dat ik de gedachte heb dat…’?",
    suggestedAction: "Noteer één terugkerende gedachte en zet ervoor: ‘Ik merk dat ik de gedachte heb dat…’.",
    sources: source("Association for Contextual Behavioral Science — ACT", "https://contextualscience.org/act"),
  }),
  item({
    id: "act-bladeren-op-de-stroom",
    title: "ACT-oefening: bladeren op de stroom",
    summary: "Een korte defusie-oefening om gedachten voorbij te laten bewegen zonder ermee te vechten.",
    topics: ["ACT", "Oefening", "Defusie", "Mindfulness"],
    keywords: ["act", "bladeren op de stroom", "gedachten loslaten", "mindfulness", "piekeren", "oefening"],
    exampleQueries: ["ACT oefening voor gedachten", "Bladeren op de stroom", "Oefening tegen piekeren", "Gedachten voorbij laten gaan"],
    paragraphs: [
      "Ga rustig zitten en merk op welke gedachten langskomen. Stel je voor dat iedere gedachte op een blad op een langzaam stromende rivier ligt.",
      "Je hoeft het blad niet weg te duwen en je hoeft het ook niet vast te houden. Als je merkt dat je meegaat in een gedachte, breng je je aandacht vriendelijk terug naar de stroom.",
      "Sommige gedachten blijven terugkomen. Dat betekent niet dat je de oefening verkeerd doet; het terugkeren is juist het oefenen.",
    ],
    reflectionQuestion: "Welke gedachte merkte je op, zonder die meteen te hoeven oplossen?",
    suggestedAction: "Doe deze oefening vijf minuten en noteer daarna wat je opviel.",
    sources: source("Association for Contextual Behavioral Science — ACT", "https://contextualscience.org/act"),
  }),
  item({
    id: "act-ruimte-maken-voor-gevoelens",
    title: "ACT: ruimte maken voor gevoelens",
    summary: "Je kunt een gevoel voorzichtig toelaten en onderzoeken zonder het groter te maken of direct weg te drukken.",
    topics: ["ACT", "Gevoelens", "Acceptatie", "Spanning"],
    keywords: ["act", "acceptatie", "gevoel toelaten", "spanning", "angst", "ruimte maken"],
    exampleQueries: ["Hoe accepteer ik gevoelens", "ACT bij spanning", "Ruimte maken voor angst", "Ik wil mijn gevoel weg hebben"],
    paragraphs: [
      "Acceptatie betekent niet dat je iets prettig moet vinden of dat je het ermee eens bent. Het betekent dat je erkent wat er nu aanwezig is, voor zover dat veilig en haalbaar is.",
      "Je kunt nieuwsgierig opmerken waar je een gevoel in je lichaam merkt, welke woorden erbij komen en wat je op dat moment nodig hebt.",
      "Soms is eerst stabiliseren, afleiding of steun zoeken passender. Bespreek sterke ontregeling met je behandelaar.",
    ],
    reflectionQuestion: "Kun je het gevoel benoemen zonder jezelf te veroordelen: ‘Er is spanning’ of ‘Ik merk angst’?",
    suggestedAction: "Neem twee minuten om een gevoel te benoemen, de plek in je lichaam op te merken en rustig uit te ademen.",
    sources: source("Association for Contextual Behavioral Science — ACT", "https://contextualscience.org/act"),
  }),
  item({
    id: "act-hier-en-nu",
    title: "ACT-oefening: terug naar het hier en nu",
    summary: "Aandacht voor je zintuigen kan helpen om los te komen van piekeren en terug te keren naar dit moment.",
    topics: ["ACT", "Mindfulness", "Hier en nu", "Aandacht"],
    keywords: ["act", "mindfulness", "hier en nu", "aandacht", "zintuigen", "gronding"],
    exampleQueries: ["ACT mindfulness oefening", "Hoe kom ik in het hier en nu", "Ik zit vast in mijn hoofd", "Gronden met ACT"],
    paragraphs: [
      "Je aandacht kan gemakkelijk naar het verleden of de toekomst gaan. ACT gebruikt aandachtsoefeningen om op te merken waar je aandacht is en die bewust terug te brengen.",
      "Kijk rustig om je heen en benoem vijf dingen die je ziet, vier dingen die je voelt, drie dingen die je hoort, twee dingen die je ruikt en één ding dat je proeft.",
      "Je hoeft je gedachten niet stil te maken. Je merkt ze op en brengt je aandacht telkens terug naar je zintuigen.",
    ],
    reflectionQuestion: "Welk zintuig hielp jou het meest om aanwezig te zijn?",
    suggestedAction: "Doe de 5-4-3-2-1-oefening één keer op een rustig moment en één keer bij lichte spanning.",
    sources: source("Association for Contextual Behavioral Science — ACT", "https://contextualscience.org/act"),
  }),
  item({
    id: "act-het-observerende-zelf",
    title: "ACT: het observerende zelf",
    summary: "Je bent niet hetzelfde als iedere gedachte, emotie of rol die je op een moment ervaart.",
    topics: ["ACT", "Zelfbeeld", "Observeren", "Defusie"],
    keywords: ["act", "observerende zelf", "zelfbeeld", "ik ben", "gedachten", "emoties"],
    exampleQueries: ["Wie ben ik volgens ACT", "Ik ben mijn diagnose", "ACT zelfbeeld", "Observerend zelf oefenen"],
    paragraphs: [
      "Je kunt merken dat je gedachten, gevoelens, lichaam en rollen in de loop van de tijd veranderen. Tegelijk is er een perspectief van waaruit je die veranderingen kunt opmerken.",
      "In plaats van ‘ik ben een mislukkeling’ kun je bijvoorbeeld oefenen met ‘ik merk dat ik de gedachte heb dat ik een mislukkeling ben’. Dat maakt de gedachte niet onwaar of waar, maar geeft meer keuzevrijheid.",
      "Deze oefening gaat niet over jezelf losmaken van je lichaam of werkelijkheid. Het gaat om een vriendelijke manier van kijken naar je innerlijke ervaringen.",
    ],
    reflectionQuestion: "Welke gedachte over jezelf zou je kunnen formuleren als: ‘Ik merk dat ik de gedachte heb dat…’?",
    suggestedAction: "Schrijf drie dingen op die je ervaart en voeg telkens toe: ‘Dit is iets wat ik opmerk; het is niet mijn hele identiteit.’",
    sources: source("Association for Contextual Behavioral Science — ACT", "https://contextualscience.org/act"),
  }),
  item({
    id: "act-waardenactie-kleine-stap",
    title: "ACT: een kleine stap in de richting van je waarden",
    summary: "Een kleine waardegerichte actie is vaak haalbaarder dan wachten tot je je volledig goed voelt.",
    topics: ["ACT", "Waarden", "Actie", "Gedragsactivatie"],
    keywords: ["act", "toegewijde actie", "kleine stap", "waarden", "beginnen", "doen"],
    exampleQueries: ["Welke ACT actie kan ik doen", "Kleine stap zetten", "ACT huiswerk", "Doen wat belangrijk is ondanks angst"],
    paragraphs: [
      "Toegewijde actie betekent dat je gedrag kiest dat past bij je waarden. De stap mag klein zijn; het gaat om richting, niet om perfectie.",
      "Maak de stap concreet: wat ga je doen, waar, wanneer en hoe lang? Houd rekening met je belastbaarheid en maak een kleinere versie als dat nodig is.",
      "Spanning of twijfel betekent niet automatisch dat je moet stoppen. Je kunt de spanning meenemen en tegelijk bijsturen als de stap niet passend of veilig is.",
    ],
    reflectionQuestion: "Welke actie van vijf tot tien minuten past bij de richting die je belangrijk vindt?",
    suggestedAction: "Plan één kleine waardegerichte actie voor deze week en noteer wat de eerste stap is.",
    sources: source("Association for Contextual Behavioral Science — ACT", "https://contextualscience.org/act"),
  }),
  item({
    id: "act-controle-en-vermijding",
    title: "ACT: wanneer controle en vermijding niet meer helpen",
    summary: "Steeds proberen gevoelens of gedachten te controleren kan op korte termijn helpen, maar op lange termijn ruimte beperken.",
    topics: ["ACT", "Vermijding", "Controle", "Coping"],
    keywords: ["act", "vermijden", "controle", "veiligheidsgedrag", "coping", "angst"],
    exampleQueries: ["Waarom blijf ik vermijden", "ACT controle loslaten", "Ik doe alles om geen angst te voelen", "Vermijding en spanning"],
    paragraphs: [
      "Iedereen probeert soms nare ervaringen te verminderen. Dat kan tijdelijk verlichting geven. Het wordt lastig wanneer vermijden of controleren steeds meer bepaalt wat je wel en niet kunt doen.",
      "Vraag jezelf niet alleen: ‘Hoe krijg ik dit gevoel weg?’, maar ook: ‘Helpt deze strategie mij op langere termijn om te leven zoals ik wil?’",
      "Het doel is niet om alle vermijding ineens te stoppen. Kies een veilige, kleine situatie waarin je iets meer ruimte kunt maken voor ervaring en gedrag.",
    ],
    reflectionQuestion: "Welke strategie geeft kort rust, maar kost je later iets?",
    suggestedAction: "Kies één kleine, veilige situatie waarin je een vermijdingsactie vijf minuten uitstelt.",
    sources: source("Association for Contextual Behavioral Science — ACT", "https://contextualscience.org/act"),
  }),
  item({
    id: "act-terugval-en-opnieuw-beginnen",
    title: "ACT: omgaan met een terugslag en opnieuw beginnen",
    summary: "Een terugslag betekent niet dat je opnieuw bij nul begint; je kunt opnieuw kijken, kiezen en bijsturen.",
    topics: ["ACT", "Terugval", "Zelfcompassie", "Herstel"],
    keywords: ["act", "terugslag", "terugval", "opnieuw beginnen", "zelfcompassie", "herstel"],
    exampleQueries: ["ACT bij terugval", "Ik heb mijn huiswerk niet gedaan", "Opnieuw beginnen", "Ik ben teleurgesteld in mezelf"],
    paragraphs: [
      "In oefenen zitten dagen waarop iets lukt en dagen waarop dat minder lukt. Een terugslag kan informatie geven over je belastbaarheid, omstandigheden en wat je nodig hebt.",
      "Probeer zelfkritiek te vervangen door een onderzoekende houding: wat gebeurde er, wat maakte het moeilijk en welke kleinere stap past nu?",
      "Je kunt opnieuw kiezen voor een waardegerichte stap zonder te wachten tot je jezelf eerst hebt vergeven of gemotiveerd voelt.",
    ],
    reflectionQuestion: "Wat zou je tegen een goede vriend zeggen die vandaag niet aan zijn oefening toekwam?",
    suggestedAction: "Kies een versie van je ACT-huiswerk die half zo klein is en plan die binnen 24 uur.",
    sources: source("Association for Contextual Behavioral Science — ACT", "https://contextualscience.org/act"),
  }),
];

export const psychoeducationSeedById = Object.fromEntries(
  psychoeducationSeed.map((record) => [record.content.id, record]),
) as Record<string, PsychoRecord>;
