import type { CSSProperties } from "react";

// Vormgeving van Home, doelkaarten en actiekaarten.
export const recoveryStyles = {
  goalName: { margin: 0, fontSize: "23px", lineHeight: 1.3, color: "#262343", overflowWrap: "anywhere", minWidth: 0, flex: 1 },
  editGoalButton: { flexShrink: 0, display: "grid", placeItems: "center", width: "40px", height: "40px", border: "1px solid #ded8ed", borderRadius: "12px", background: "#fff", color: "#6253a0", cursor: "pointer" },
  nestedActions: { paddingLeft: "12px", borderLeft: "3px solid #d5ccef", marginTop: "18px", minWidth: 0 },
  newGoalButton: { width: "100%", padding: "17px 18px", margin: "0 0 24px", border: "1px dashed #9687c5", borderRadius: "16px", color: "#55458b", background: "#f5f1ff", fontSize: "16px", fontWeight: 700, cursor: "pointer" },
  addActionButton: { width: "100%", marginTop: "16px", padding: "12px", borderRadius: "12px", border: "1px solid #ddd4f2", background: "#f7f4ff", color: "#55458b", fontWeight: 700, cursor: "pointer" },
  completedToggle: { display: "flex", alignItems: "center", gap: "6px", border: 0, background: "transparent", padding: "10px 0", color: "#6d657e", fontSize: "13px", cursor: "pointer" },
  selectedResourceCard: { background: "#ece6fa", borderColor: "#9d8bc8" },
  resourceOptions: { marginTop: "16px", padding: "16px", borderRadius: "16px", background: "#faf8ff", border: "1px solid #e4ddef" },
  templateButton: { width: "100%", textAlign: "left", padding: "13px", border: "1px solid #e3ddef", borderRadius: "12px", background: "#fff", color: "#423858", cursor: "pointer", fontSize: "14px", overflowWrap: "anywhere" },
  learningLinks: { display: "grid", gap: "12px", marginTop: "18px" },
  actionTitleButton: { textAlign: "left", border: 0, background: "transparent", padding: "4px 0", color: "inherit", cursor: "pointer", fontFamily: "inherit" },
  actionDetails: { display: "grid", gap: "6px", marginTop: "8px" },
  title: {
    color: "#262343",
    fontSize: "29px",
    fontWeight: 800,
    letterSpacing: "-0.8px",
    lineHeight: 1.2,
    margin: "0 0 16px",
  },
  intro: {
    color: "#66617f",
    fontSize: "16px",
    lineHeight: 1.58,
    margin: "0 0 26px",
    backgroundColor: "rgba(255, 255, 255, 0.88)",
    border: "1px solid rgba(210, 203, 238, 0.72)",
    borderRadius: "8px 22px 22px 22px",
    padding: "16px 17px",
    textAlign: "left",
    boxShadow: "0 8px 22px rgba(73, 62, 130, 0.07)",
  },
  primaryButton: {
    width: "100%",
    border: 0,
    borderRadius: "18px",
    background: "linear-gradient(135deg, #5657df 0%, #6f5ee7 100%)",
    color: "#ffffff",
    fontSize: "16px",
    fontWeight: 800,
    padding: "16px 20px",
    cursor: "pointer",
    marginTop: "14px",
    boxShadow: "0 10px 24px rgba(82, 78, 205, 0.26)",
  },
  immediateActionFooter: {
    marginTop: "18px",
    paddingTop: "14px",
    borderTop: "2px solid #e5e0f2",
  },
  disabledButton: {
    opacity: 0.45,
    cursor: "not-allowed",
  },
  textButton: {
    border: 0,
    background: "transparent",
    color: "#5954ca",
    fontWeight: 800,
    cursor: "pointer",
    padding: "6px",
  },
  restartOnboardingButton: {
    width: "100%",
    border: 0,
    borderTop: "1px solid #e8e3f3",
    background: "transparent",
    color: "#77708d",
    fontSize: "13px",
    fontWeight: 700,
    padding: "17px 10px 4px",
    marginTop: "24px",
    cursor: "pointer",
  },
  smallButton: {
    border: 0,
    borderRadius: "999px",
    backgroundColor: "#e9e5ff",
    color: "#544db2",
    fontWeight: 800,
    padding: "10px 14px",
    cursor: "pointer",
  },
  goalCard: {
    background: "linear-gradient(145deg, #fff0f5 0%, #f0ecff 100%)",
    border: "1px solid rgba(174, 148, 226, 0.2)",
    borderRadius: "24px",
    padding: "20px",
    margin: "23px 0 28px",
    boxShadow: "0 10px 28px rgba(99, 76, 147, 0.09)",
  },
  goalTitleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  },
  goalTitle: {
    margin: 0,
    color: "#383257",
    fontSize: "18px",
    lineHeight: 1.35,
  },
  goalText: {
    margin: "15px 0 0",
    color: "#353151",
    fontSize: "16px",
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
  },
  sectionHeadingRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "12px",
  },
  sectionTitle: {
    fontSize: "19px",
    color: "#302b50",
    fontWeight: 800,
    margin: 0,
  },
  emptyCard: {
    border: "1px dashed #cfc7ee",
    borderRadius: "18px",
    backgroundColor: "rgba(255, 255, 255, 0.55)",
    color: "#7f7895",
    padding: "17px",
    fontSize: "14px",
  },
  actionList: {
    display: "flex",
    flexDirection: "column",
    gap: "11px",
  },
  actionItemGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "7px",
  },
  actionCard: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: "12px",
    border: "1.5px solid #e1dcf6",
    borderRadius: "18px",
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    color: "#3a3556",
    padding: "15px",
    fontSize: "15px",
    textAlign: "left",
    cursor: "pointer",
    boxShadow: "0 7px 18px rgba(67, 57, 122, 0.07)",
  },
  actionBody: {
    minWidth: 0,
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  actionCategoryLabel: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    color: "#6c65a5",
    fontSize: "11px",
    fontWeight: 900,
    letterSpacing: "0.35px",
    textTransform: "uppercase",
  },
  actionResourceLink: {
    alignSelf: "flex-start",
    marginLeft: "48px",
    color: "#5b54c3",
    fontSize: "12px",
    fontWeight: 800,
    textDecoration: "none",
  },
  mindfulnessActionButton: {
    alignSelf: "flex-start",
    marginLeft: "48px",
    border: 0,
    background: "transparent",
    color: "#3f8a76",
    fontFamily: "inherit",
    fontSize: "12px",
    fontWeight: 900,
    padding: 0,
    cursor: "pointer",
  },
  actionActBadge: {
    flexShrink: 0,
    borderRadius: "8px",
    background: "linear-gradient(145deg, #ff89a8, #ffb07e)",
    color: "#46335b",
    fontSize: "9px",
    fontWeight: 900,
    letterSpacing: "0.4px",
    padding: "5px 6px",
  },
  actModuleCard: {
    width: "100%",
    boxSizing: "border-box",
    border: "1.5px solid #dcd5f6",
    borderRadius: "22px",
    background: "linear-gradient(145deg, #f1edff, #fff0f5)",
    color: "#3a3556",
    padding: "17px",
    boxShadow: "0 10px 24px rgba(67, 57, 122, 0.1)",
  },
  actModuleHeader: {
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    marginBottom: "14px",
  },
  actModuleTitleGroup: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  actModuleTitle: {
    color: "#37315d",
    fontSize: "16px",
    lineHeight: 1.35,
  },
  actModuleSubtitle: {
    color: "#756e8d",
    fontSize: "13px",
    lineHeight: 1.4,
  },
  actVersionLink: {
    alignSelf: "flex-start",
    border: 0,
    background: "transparent",
    color: "#5b54c3",
    fontSize: "12px",
    fontWeight: 800,
    lineHeight: 1.4,
    padding: "2px 0",
    textAlign: "left",
    cursor: "pointer",
  },
  actModuleButtons: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "9px",
    marginTop: "15px",
  },
  actReadButton: {
    border: "1.5px solid #625bdd",
    borderRadius: "14px",
    backgroundColor: "rgba(255, 255, 255, 0.86)",
    color: "#554fc1",
    fontSize: "14px",
    fontWeight: 900,
    padding: "12px 10px",
    cursor: "pointer",
  },
  actDailyButton: {
    border: 0,
    borderRadius: "14px",
    background: "linear-gradient(135deg, #5757dd, #7a62e8)",
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: 900,
    padding: "12px 10px",
    cursor: "pointer",
    boxShadow: "0 7px 16px rgba(82, 78, 205, 0.2)",
  },
  dailyCompletedLabel: {
    display: "block",
    marginTop: "12px",
    borderRadius: "12px",
    backgroundColor: "rgba(97, 199, 164, 0.16)",
    color: "#2f7861",
    fontSize: "13px",
    fontWeight: 800,
    padding: "9px 11px",
  },
  actionProgressBlock: {
    display: "flex",
    flexDirection: "column",
    gap: "5px",
  },
  actionProgressLabelRow: {
    display: "flex",
    justifyContent: "space-between",
    color: "#766f92",
    fontSize: "11px",
  },
  actionProgressTrack: {
    width: "100%",
    height: "7px",
    overflow: "hidden",
    borderRadius: "999px",
    backgroundColor: "#e7e3f3",
  },
  actionProgressFill: {
    display: "block",
    height: "100%",
    borderRadius: "999px",
    background: "linear-gradient(90deg, #625bdd, #ff91aa)",
    transition: "width 300ms ease",
  },
  selectedActionCard: {
    border: "2px solid #6460dc",
    backgroundColor: "#f0edff",
    padding: "14.5px",
    boxShadow: "0 9px 22px rgba(91, 84, 204, 0.14)",
  },
  checkbox: {
    width: "24px",
    height: "24px",
    flexShrink: 0,
    border: "2px solid #aaa3cc",
    borderRadius: "8px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: "#ffffff",
    fontWeight: 900,
  },
  selectedCheckbox: {
    backgroundColor: "#5b58d9",
    borderColor: "#5b58d9",
  },
  actionText: {
    lineHeight: 1.45,
  },
  completeArea: {
    marginTop: "14px",
    padding: "16px",
    borderRadius: "20px",
    background: "linear-gradient(145deg, #fff0d9, #ffe5ef)",
    border: "1px solid rgba(241, 166, 109, 0.2)",
  },
  helperText: {
    color: "#65566b",
    fontSize: "14px",
    lineHeight: 1.45,
    margin: "0 0 10px",
  },
  completeButton: {
    width: "100%",
    border: 0,
    borderRadius: "15px",
    background: "linear-gradient(135deg, #ff7e9c, #ff9b82)",
    color: "#ffffff",
    fontSize: "15px",
    fontWeight: 800,
    padding: "13px",
    cursor: "pointer",
    boxShadow: "0 8px 20px rgba(229, 104, 133, 0.22)",
  },
  completedSection: {
    marginTop: "32px",
    paddingTop: "24px",
    borderTop: "1px solid #e6e1f3",
  },
  resourcesSection: {
    marginTop: "32px",
    paddingTop: "24px",
    borderTop: "1px solid #e6e1f3",
  },
  resourcesGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "9px",
    marginTop: "13px",
  },
  resourceCard: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "7px",
    border: "1px solid #e0daf5",
    borderRadius: "18px",
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    color: "#39345c",
    padding: "12px 9px",
    textAlign: "left",
    textDecoration: "none",
    cursor: "pointer",
    boxShadow: "0 7px 18px rgba(67, 57, 122, 0.07)",
  },
  resourceIcon: {
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "11px",
    color: "#ffffff",
    fontSize: "13px",
    fontWeight: 900,
  },
  informationIcon: {
    background: "linear-gradient(145deg, #5a87df, #7264e8)",
  },
  practiceIcon: {
    background: "linear-gradient(145deg, #5fc39e, #5aaec5)",
  },
  contactIcon: {
    background: "linear-gradient(145deg, #ff829f, #ff9f82)",
    fontSize: "10px",
    letterSpacing: "-1px",
  },
  resourceTitle: {
    color: "#3b355d",
    fontSize: "13px",
  },
  resourceText: {
    color: "#77708d",
    fontSize: "10px",
    lineHeight: 1.35,
  },
  emptyCompletedText: {
    color: "#8b859d",
    fontSize: "14px",
    fontStyle: "italic",
    margin: "12px 0 0",
  },
  completedActionCard: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    borderRadius: "18px",
    backgroundColor: "#eeecf5",
    color: "#77728a",
    padding: "15px",
    marginTop: "12px",
  },
  completedCheck: {
    width: "24px",
    height: "24px",
    flexShrink: 0,
    borderRadius: "50%",
    background: "linear-gradient(145deg, #6bc8aa, #67b6c8)",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 900,
  },
  completedActionBody: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  completedActionCategory: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    color: "#817b92",
    fontSize: "10px",
    fontWeight: 900,
    textTransform: "uppercase",
  },
  completedActionText: {
    textDecoration: "line-through",
    lineHeight: 1.45,
  },
  inputFull: {
    width: "100%",
    boxSizing: "border-box",
    border: "1.5px solid #d7d0f0",
    borderRadius: "16px",
    padding: "14px",
    fontSize: "15px",
    color: "#302c4e",
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    outlineColor: "#6964df",
    marginBottom: "20px",
  },
  label: {
    display: "block",
    color: "#4b456d",
    fontSize: "14px",
    fontWeight: 800,
    margin: "20px 0 8px",
  },
  actionMetaStack: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    margin: "0 0 14px",
  },
  actionMetaLine: {
    display: "flex",
    alignItems: "flex-start",
    gap: "6px",
    color: "#756f88",
    fontSize: "12px",
    fontWeight: 600,
    lineHeight: 1.4,
  },
  recurringCompletedLabel: {
    alignSelf: "flex-start",
    borderRadius: "999px",
    backgroundColor: "#e6f6ef",
    color: "#2f7861",
    fontSize: "11px",
    fontWeight: 900,
    padding: "6px 9px",
  },
} satisfies Record<string, CSSProperties>;
